### ISSUE TITLE
Suppress Warnings

### ISSUE THREAD

**Issue by kruegers** [eclipse-cognicrypt/CogniCrypt#189]
Extend the static-analysis plugin such that the user may suppress warnings. Any suppressed warning should just be removed. Make CogniCrypt maintain one list per project that includes all suppressed warnings.

**Comment by ericbodden** [comment]
I am reopening this for further discussion. The suppression currently works, but it does not introduce explicit annotations in the code. I think it rather should, so that there is a hint that something _was_ suppressed. For instance, we could annotate the innermost block/method with @SuppressWarning("<WarningKind>") where <WarningKind> gives some information about what kind of warning was suppressed.

**Comment by kruegers** [comment]
I don't really mind the way it is setup, but am fine with your suggestion, too, @ericbodden. We initially opted for this implementation because we did not want to introduce custom annotations. Since we are doing that now anyways, that hurdle is no longer there, anyways.

@AndreSonntag Given your work on #209 and CROSSINGTUD/CryptoAnalysis#80, you should be well-equippted to implement this extension, so please do. That said, please do as we agreed on Tuesday first, then take care of issue #212, and only ofter that come back to this issue here. Thanks!

**Comment by AndreSonntag** [comment]
There is a problem regarding annotations in general. Every annotation is subject to certain targets (see https://docs.oracle.com/javase/10/docs/api/java/lang/annotation/ElementType.html).
No one of the types allowed to add an annotation to a method invocation.

Example:
![image](https://user-images.githubusercontent.com/31883471/47912268-53f8a700-de98-11e8-9401-dd225799d84d.png)

In this example is it possible to add an annotation to the `IvParameterSpec` object what is fine, but not to the `init` call. The problem is the mentioned before issue regarding the target types of annotations. I couldn't find a way to extend the target type list.

One solution could be to add the @SuppressWarnings annotation on the method head, like in the following example.

![image](https://user-images.githubusercontent.com/31883471/47913087-147f8a00-de9b-11e8-9ac4-256db53106b8.png)

Or with a custom annotation

![image](https://user-images.githubusercontent.com/31883471/47913098-22cda600-de9b-11e8-93ea-16e9f85baac1.png)

**Comment by kruegers** [comment]
Correct me if I'm wrong, but didn't we say, we would generate the annotation either to the allocation site of the insecure object, if it is in the same method as the call, or to the parameter, if not?

**Comment by ericbodden** [comment]
Hi all.

I think it might help to see how the checker framework uses annotations: https://checkerframework.org/

A simple solution would be to annotate the whole error-containing method but I agree that this is not optimal. I like the idea of annotating alloc sites.

**Comment by kruegers** [comment]
assigned @AndreSonntag.

**Comment by AndreSonntag** [comment]
Info’s regarding the latest problems of the suppresswarning function: 

I recognised, that from time to time suppressed variables have returned. Problem was the calculation of the hash values of the error objects. The hash value contained Jimple variables which sometimes changed the name, due to optimization etc. The consequence was unstable values.

I fixed the problem on the cryptoanalysis side with new tailored hashCode methods for each error type (see https://github.com/CROSSINGTUD/CryptoAnalysis/pull/150) Furthermore I deleted the hashCode helper class on the CogniCrypt plugin side because the class was obsolete.
