### ISSUE TITLE
(Possibly) Extend CrySL rules about JSSE

### ISSUE THREAD

**Issue by kruegers** [eclipse-cognicrypt/CogniCrypt#212]
Double-check the JSSE-related CrySL rules by examining whether they cover constraints four to seven of [RigoritiyJ](https://arxiv.org/pdf/1806.06881.pdf). Update them, if not. 

For bookkeeping:
- [x] Constraint 4 checked
- [x] Constraint 5 checked
- [x] Constraint 6 checked
- [x] Constraint 7 checked

- [ ] Constraint 4 covered
- [ ] Constraint 5 covered
- [ ] Constraint 6 covered
- [ ] Constraint 7 covered

**Comment by rbonifacio** [comment]
Hi, after reading the RigoritiyJ paper, I am wondering that, to specify rules (4), (5), and (6),  we would have to forbid a code like this (considering fourth rule): 

`HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
        public boolean verify(String arg0, SSLSession arg1) {
            return true;
        }
    });`

At this moment, I know how to state in CrySL that a method mustn't be called (using the forbidden clause). As such, we could state that a call to the method `setDefaultHostnameVerifier` is not allowed. 
Nevertheless, I think that this approach would lead to an overly constraint, which might lead to false positives in the end.

**Comment by kruegers** [comment]
assigned @AndreSonntag.

**Comment by AndreSonntag** [comment]
Rule 4 – Detection of abuse of the `javax.net.ssl.HostnameVerifier` Interface
---
During handshaking, if the URL's hostname and the server's identification hostname mismatch, the verification mechanism can call back to implementers of this interface to determine if this connection should be allowed. [[1](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/HostnameVerifier.html)]

`boolean verify(String hostname, SSLSession session) `

The RIGORITYJ rule checks how the method is implemented. I guess a misuse would be if the user would simply return `true`.

Rule 5 – Detection of abuse of the `javax.net.ssl.X509TrustManager` Interface
---
Instance of this interface manage which X509 certificates may be used to authenticate the remote side of a secure socket. Decisions may be based on trusted certificate authorities, certificate revocation lists, online status checking or other means. [[2](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/X509TrustManager.html)]

The RIGORITYJ rule detects three concrete cases:
1. throwing no exception after validating a certificate in `checkServerTrusted`
2. unpinned self-signed certiﬁcate with an expiration check
3. not providing a valid list of certiﬁcates in` getAcceptedIssuers`.

The authors write that they search for the occurrences of `throw` or propagated exception for the first case. The other two cases are not described. I guess they are validating the method implementation again.

Rule 6 – Directly use of a `javax.net.ssl.SSLSocket` object without performing a hostname verification
---
SSLSocket API description [[3]( https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSocket.html)]
 
The RIGORITYJ authors just describe how they track a `SSLSocket` object. It is not relevant to mention here.

Rule 7 – Occasional use of HTTP
---
No description in the paper.

Summary
---
Rule 4, 5 and 6 are not realizable in CrySL, because they are check the concrete implementation. I don’t know what the authors check in rule 7.

**Comment by kruegers** [comment]
Cannot cover any of the rules in CrySL. Closing this issue. Thanks @AndreSonntag for checking this out.
