### ISSUE TITLE
Crysl rules for Order not working properly when call sequence is within try{} block

### ISSUE THREAD

**Issue by j-braun** [eclipse-cognicrypt/CogniCrypt#416]
**Describe the bug**
The CRYSL file for our API contains the ORDER section containing "Cons, Nexts+" which resolves to "there must be a call to the constructor of the class, and then at least one call to one of the contained methods."
Within the souce code, the correct call sequence is within a try{} block, which leads to the error 
Operation on object of type prngCombiners.PrngCombAes object not completed. Expected call to generateSeed, prngCombiners.PrngCombAes: void nextBytes(byte[])
outside of a try block no error is shown. The error also vanishes if the order rule is changed to "Cons, Nexts*"

**To Reproduce**
take a correct call sequence of the above form and put it in a try{} block

**Expected behavior**
No error should be shown

**Screenshots**
error shown here
![grafik](https://user-images.githubusercontent.com/10594832/102226574-d44bbc00-3ee8-11eb-8f6d-952b8e469e72.png)
but no error here
![grafik](https://user-images.githubusercontent.com/10594832/102226686-f80f0200-3ee8-11eb-92a9-0cbdbdf3d569.png)

**Additional context**
Cognicrypt running from sources
Eclipse Platform
Version: 2019-06 (4.12)
Build id: I20190605-1800
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 1.8.0_271

**Comment by schlichtig** [comment]
This issue you are describing is technically a true positive. Since, a try{} block can fail (only decided at runtime), it is not guaranteed (from the perspective of the analysis) that the call to the second method is made.
The static analysis considers all pathes and when at least one path like when the try{} block fails, it will report the issue. Thus, it is a true positive. Albeit in this case one could consider it to be an "effective false positive."
Therefore, I will close this issue.
